version: "3"

services:
  
  
  send:
    image: '${DOCKER_SEND_IMAGE}'
    restart: always
    ports:
      - '8081:8080' # le port 8081 est exposé sur l'hôte et le 8080 est exposé sur le conteneur
    volumes:
      - ./uploads:/uploads
      - ./custom_assets:/app/dist/custom_assets
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=8080 # le port 8080 est exposé sur le conteneurœ
      - DHPARAM_GENERATION=false
      #- LETSENCRYPT_HOST
      #- LETSENCRYPT_EMAIL
      - NODE_ENV=production
      - BASE_URL=${SEND_BASE_URL}
      - PORT=8080 # le port 8080 est exposé sur le conteneur
      - REDIS_HOST=redis
      - CUSTOM_TITLE=HIsend
      - UI_CUSTOM_ASSETS_ICON=custom_assets/brandhi.png
      - CUSTOM_FOOTER_TEXT=Ceci est un outil mis à disposition par l'équipe Cyber d'Handicap International.
      - SEND_FOOTER_SOURCE_URL=https://hi.org
      - UI_CUSTOM_ASSETS_FAVICON_16PX=custom_assets/logo_hi.ico
      - UI_CUSTOM_ASSETS_FAVICON_32PX=custom_assets/logo_hi.ico
      - UI_CUSTOM_ASSETS_WORDMARK=none
      - UI_COLOR_PRIMARY=#0077c8
      - UI_COLOR_ACCENT=#06038d
      - EXPIRE_TIMES_SECONDS=300,3600,86400
      - DOWNLOAD_COUNTS=1,2,3,4,5,10,15,25
      - UI_CUSTOM_CSS=custom_assets/style.css

      # For local uploads storage
      - FILE_DIR=/uploads

      # For S3 object storage (disable volume and FILE_DIR variable)
      # - AWS_ACCESS_KEY_ID=********
      # - AWS_SECRET_ACCESS_KEY=********
      # - S3_BUCKET=send
      # - S3_ENDPOINT=s3.us-west-2.amazonaws.com
      # - S3_USE_PATH_STYLE_ENDPOINT=true

      # To customize upload limits
      # - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000,31536000
      # - DEFAULT_EXPIRE_SECONDS=3600
      # - MAX_EXPIRE_SECONDS=31536000
      # - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000
      # - MAX_DOWNLOADS=1000
      # - MAX_FILE_SIZE=2684354560
  
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - send-redis:/data

volumes:
  send-redis:
  proxy-certs:
  proxy-vhost:
  proxy-html:
